import { defineProvider } from './core.ts';

export const BUILTIN_PROVIDER_DEFINITIONS = [
  defineProvider({
    schemaVersion: 1,
    version: '1.0.0',
    id: 'codex',
    displayName: 'Codex',
    description: 'Automatic project conversation capture.',
    providerType: 'coding-agent',
    documentationUrl: 'https://learn.chatgpt.com/docs/hooks',
    discovery: { executables: ['codex'], versionCommand: ['codex', '--version'], configPaths: ['.codex/hooks.json'] },
    auth: { type: 'existing-session' },
    eventSource: { type: 'hooks', projectConfigPath: '.codex/hooks.json' },
    events: {
      SessionStart: { canonical: 'session.started' },
      UserPromptSubmit: { canonical: 'user.message', contentPath: 'prompt' },
      PostToolUse: { canonical: 'tool.completed' },
      Stop: { canonical: 'assistant.message', contentPath: 'last_assistant_message' },
      SessionEnd: { canonical: 'session.ended' },
    },
    finalization: { strategy: 'explicit-event', event: 'SessionEnd' },
    verification: { required: ['user.message', 'assistant.message'], optional: ['tool.completed'], requireTranscript: true },
  }),
  defineProvider({
    schemaVersion: 1,
    version: '1.0.0',
    id: 'codebuddy',
    displayName: 'CodeBuddy',
    description: 'Lifecycle hook and official transcript import.',
    providerType: 'coding-agent',
    discovery: { executables: ['codebuddy'], configPaths: ['.codebuddy/settings.json'] },
    auth: { type: 'existing-session' },
    eventSource: { type: 'hooks', projectConfigPath: '.codebuddy/settings.json' },
    events: {
      SessionStart: { canonical: 'session.started' },
      UserPromptSubmit: { canonical: 'user.message', contentPath: 'prompt' },
      PreToolUse: { canonical: 'tool.started' },
      PostToolUse: { canonical: 'tool.completed' },
      Stop: { canonical: 'assistant.message', contentPath: 'last_assistant_message' },
      SessionEnd: { canonical: 'session.ended' },
    },
    finalization: { strategy: 'explicit-event', event: 'SessionEnd' },
    verification: { required: ['user.message', 'assistant.message'], optional: ['tool.completed'], requireTranscript: true },
  }),
  defineProvider({
    schemaVersion: 1,
    version: '1.0.0',
    id: 'opencode',
    displayName: 'OpenCode',
    description: 'Plugin event stream with semantic merge.',
    providerType: 'coding-agent',
    discovery: { executables: ['opencode'], pluginPaths: ['.opencode/plugins/awb-capture.js'] },
    auth: { type: 'none' },
    eventSource: { type: 'plugin', projectConfigPath: '.opencode/plugins/awb-capture.js' },
    events: {},
    transformer: { type: 'builtin', name: 'opencode' },
    finalization: { strategy: 'session-idle', limitation: 'Streaming events are merged by message ID.' },
    verification: { required: ['user.message', 'assistant.message'], optional: ['tool.completed'], requireTranscript: true },
  }),
  defineProvider({
    schemaVersion: 1,
    version: '1.0.0',
    id: 'trae',
    displayName: 'Trae',
    description: 'Workspace hooks awaiting a real IDE event.',
    providerType: 'ide-agent',
    discovery: { executables: ['trae-cn'], configPaths: ['.trae/hooks.json'] },
    auth: { type: 'existing-session' },
    eventSource: { type: 'hooks', projectConfigPath: '.trae/hooks.json' },
    events: {
      SessionStart: { canonical: 'session.started' },
      UserPromptSubmit: { canonical: 'user.message', contentPath: 'prompt' },
      PostToolUse: { canonical: 'tool.completed' },
      Stop: { canonical: 'assistant.message', contentPath: 'last_assistant_message' },
    },
    finalization: { strategy: 'custom', limitation: 'This build has no SessionEnd event.' },
    verification: { required: ['user.message', 'assistant.message'], optional: ['tool.completed'], requireTranscript: true },
  }),
  defineProvider({
    schemaVersion: 1,
    version: '1.0.0',
    id: 'codearts',
    displayName: 'CodeArts',
    description: 'CLI export after access-key authentication.',
    providerType: 'coding-agent',
    discovery: { executables: ['codearts'] },
    auth: { type: 'ak-sk', fields: ['CODEARTS_CLI_AK', 'CODEARTS_CLI_SK'], verifyCommand: ['codearts', 'session', 'list'] },
    eventSource: { type: 'export-import' },
    events: {},
    finalization: { strategy: 'manual' },
    verification: { required: ['user.message', 'assistant.message'], requireTranscript: true },
  }),
  defineProvider({
    schemaVersion: 1,
    version: '1.0.0',
    id: 'chatgpt',
    displayName: 'ChatGPT',
    description: 'User-provided transcript import only.',
    providerType: 'chat-product',
    discovery: {},
    auth: { type: 'manual' },
    eventSource: { type: 'manual-import' },
    events: {},
    finalization: { strategy: 'manual' },
    verification: { required: [], requireTranscript: false },
  }),
  defineProvider({
    schemaVersion: 1,
    version: '1.0.0',
    id: 'workbuddy',
    displayName: 'WorkBuddy',
    description: 'Provider integration not installed on this machine.',
    providerType: 'coding-agent',
    discovery: {},
    auth: { type: 'external' },
    eventSource: { type: 'custom' },
    events: {},
    finalization: { strategy: 'custom', limitation: 'No verified local WorkBuddy adapter is installed.' },
    verification: { required: ['user.message', 'assistant.message'], requireTranscript: true },
  }),
] as const;
