import { useEffect, useRef, useState } from 'react';
import { Plus, RefreshCw, ShieldCheck } from 'lucide-react';
import { assetClient, type ProviderDetailView, type ProviderStatusView } from '../services/assetClient';

export function ProviderManager() {
  const [providers, setProviders] = useState<ProviderStatusView[]>([]); const [selected, setSelected] = useState<string>('codex'); const selectedRef = useRef('codex'); const [detail, setDetail] = useState<ProviderDetailView | null>(null); const [message, setMessage] = useState(''); const [addOpen, setAddOpen] = useState(false); const [ak, setAk] = useState(''); const [sk, setSk] = useState('');
  const reload = async () => { const list = await assetClient.providers(); setProviders(list); const id = selectedRef.current || list[0]?.provider; if (id) { const next = await assetClient.providerDetail(id); if (selectedRef.current === id) setDetail(next); } };
  useEffect(() => { void reload(); }, []);
  const choose = async (id: string) => { selectedRef.current = id; setSelected(id); setDetail(null); const next = await assetClient.providerDetail(id); if (selectedRef.current === id) setDetail(next); setMessage(''); };
  const action = async (name: string, body: Record<string, unknown> = {}) => { try { const result = await assetClient.providerAction(selected, name, body); setMessage(result.detail ?? (name === 'credentials' ? '凭据已保存到操作系统安全凭据库。' : '操作完成。')); await reload(); } catch (e) { setMessage((e as Error).message); } };
  return <main className="page provider-manager"><section className="topbar"><div><p className="eyebrow">Provider Manager</p><h1>连接并管理 AI 会话采集</h1><p>从安装、认证到实时验证都在这里完成；历史聊天不会因停用而删除。</p></div><div className="hero-actions"><button className="secondary-button" onClick={() => void reload()}><RefreshCw size={16}/>重新检测</button><button className="primary-button" onClick={() => setAddOpen(!addOpen)}><Plus size={16}/>添加 Provider</button></div></section>
    {addOpen ? <CustomProvider onSaved={async () => { setAddOpen(false); await reload(); }} /> : null}
    <section className="provider-grid"><div className="panel"><h2>Provider 总览</h2><div className="provider-table"><div className="provider-head">Provider · 安装 · 认证 · 接入 · 实时 · E2E · 状态</div>{providers.map((item) => { const status = item.provider === 'codearts' && item.status === 'BLOCKED' ? 'BLOCKED_AUTH' : item.provider === 'trae' && !item.runtimeVerified ? 'WAITING_REAL_EVENT' : item.status; return <button key={item.provider} className={`provider-row ${selected === item.provider ? 'selected' : ''}`} onClick={() => void choose(item.provider)}><strong>{item.provider}</strong><span>{item.installed === false ? '未安装' : '已安装'}</span><span>{item.runtimeVerified ? 'E2E PASS' : status}</span><span className={`status-badge ${(status ?? '').toLowerCase().replace('_','-')}`}>{status}</span></button>; })}</div></div>
    <div className="panel provider-detail">{detail ? <><div className="section-heading"><div><p className="eyebrow">{detail.definition.providerType}</p><h2>{detail.definition.displayName}</h2><p>{detail.definition.description}</p></div><span className={`status-badge ${detail.status.platformStatus.toLowerCase().replace('_','-')}`}>{detail.status.platformStatus}</span></div><div className="provider-facts"><span>安装：{detail.status.installed === false ? '未安装' : '已安装'}</span><span>版本：{detail.status.version ?? '—'}</span><span>认证：{detail.status.authStatus}</span><span>事件入口：{detail.definition.eventSource.type}</span><span>结束方式：{detail.definition.finalization.strategy}</span><span>实时验证：{detail.status.runtimeVerified ? '已通过' : '等待真实会话'}</span></div>
      {selected === 'codearts' ? <div className="credential-box"><h3>访问密钥</h3><p>凭据保存在操作系统安全凭据库；页面不会回显旧值，也不会写入项目、日志或聊天记录。</p><span>Access Key：{detail.status.authStatus === 'CONFIGURED' ? '已配置' : '未配置'}</span><span>Secret Key：{detail.status.authStatus === 'CONFIGURED' ? '已配置' : '未配置'}</span><input aria-label="Access Key" type="password" value={ak} onChange={(e) => setAk(e.target.value)} placeholder="Access Key"/><input aria-label="Secret Key" type="password" value={sk} onChange={(e) => setSk(e.target.value)} placeholder="Secret Key"/><button className="secondary-button" onClick={() => void action('credentials', { CODEARTS_CLI_AK: ak, CODEARTS_CLI_SK: sk })}>{detail.status.authStatus === 'CONFIGURED' ? '更新凭据' : '保存凭据'}</button><button className="secondary-button" onClick={() => void action('delete-credentials')}>删除凭据</button><button className="primary-button" onClick={() => void action('verify-auth')}>测试连接</button></div> : null}
      <div className="hero-actions"><button className="secondary-button" onClick={() => void action(detail.status.enabled ? 'disable' : 'enable')}>{detail.status.enabled ? '停用采集' : '启用采集'}</button><button className="primary-button" onClick={() => void reload()}><ShieldCheck size={16}/>运行验证</button></div>{message ? <p className="provider-message">{message}</p> : null}
      <h3>验证结果</h3><div className="skeleton-rows">{detail.verification.map((row) => <div className="skeleton-row" key={row.step}><strong>{row.step}</strong><span>{row.detail}</span><span className={`status-badge ${row.status.toLowerCase()}`}>{row.status}</span></div>)}</div><details><summary>高级技术详情</summary><p>配置路径：{detail.definition.eventSource.projectConfigPath ?? '无需项目配置'}</p><pre>{JSON.stringify(detail.definition.events, null, 2)}</pre><p>{detail.definition.finalization.limitation ?? '会话结束策略由 Provider 事件确认。'}</p></details></> : <p>正在读取 Provider 状态…</p>}</div></section></main>;
}
function CustomProvider({ onSaved }: { onSaved: () => Promise<void> }) {
  const [name, setName] = useState(''); const [id, setId] = useState(''); const [exe, setExe] = useState(''); const [versionCommand, setVersionCommand] = useState(''); const [configPath, setConfigPath] = useState(''); const [authType, setAuthType] = useState('manual'); const [eventSource, setEventSource] = useState('custom'); const [finalization, setFinalization] = useState('manual'); const [error, setError] = useState('');
  return <section className="panel custom-provider"><h2>添加自定义 Provider</h2><p>通用映射适合明确的消息事件；流式内容和非标准结束语义会保留为“需要专用适配器”。</p><input aria-label="Provider name" value={name} onChange={(e) => setName(e.target.value)} placeholder="名称"/><input aria-label="Provider id" value={id} onChange={(e) => setId(e.target.value)} placeholder="Provider ID，例如 my-agent"/><input aria-label="Executable" value={exe} onChange={(e) => setExe(e.target.value)} placeholder="可执行文件（可选）"/><input aria-label="Version command" value={versionCommand} onChange={(e) => setVersionCommand(e.target.value)} placeholder="版本命令，例如 my-agent --version"/><input aria-label="Config path" value={configPath} onChange={(e) => setConfigPath(e.target.value)} placeholder="配置路径（可选）"/><label>认证<select aria-label="Auth type" value={authType} onChange={(e) => setAuthType(e.target.value)}><option value="manual">手动</option><option value="existing-session">已有登录态</option><option value="api-key">API Key</option><option value="ak-sk">Access/Secret Key</option></select></label><label>事件来源<select aria-label="Event source" value={eventSource} onChange={(e) => setEventSource(e.target.value)}><option value="custom">自定义</option><option value="hooks">Hooks</option><option value="plugin">Plugin</option><option value="event-stream">Event Stream</option><option value="cli-json">CLI JSON</option><option value="export-import">导出/导入</option></select></label><label>结束策略<select aria-label="Finalization strategy" value={finalization} onChange={(e) => setFinalization(e.target.value)}><option value="manual">手动</option><option value="explicit-event">明确结束事件</option><option value="session-idle">会话空闲</option><option value="next-session">下一会话</option></select></label><button className="primary-button" onClick={async () => { try { await assetClient.saveCustomProvider({ schemaVersion: 1, version: '1.0.0', id, displayName: name, description: 'Custom Provider', providerType: 'custom', discovery: { executables: exe ? [exe] : [], versionCommand: versionCommand ? versionCommand.split(/\s+/) : undefined, configPaths: configPath ? [configPath] : [] }, auth: { type: authType }, eventSource: { type: eventSource, projectConfigPath: configPath || undefined }, events: {}, finalization: { strategy: finalization, limitation: 'Generic mapping requires explicit validation before realtime capture.' }, verification: { required: [], requireTranscript: false } }); await onSaved(); } catch (e) { setError((e as Error).message); } }}>保存 Definition</button>{error ? <p>{error}</p> : null}</section>;
}
